#! /usr/bin/env python

from subprocess import call;
import sys;

migrate_cmd = "./node_modules/migrate/bin/migrate";
options = ['-c', 'components/database'];
command = ["node"] + [migrate_cmd] + options + sys.argv[1:len(sys.argv)];

#print(command);

call(command);