#! /usr/bin/env node

'use-strict';

var rootdir     = process.env.SCENE_STUDIO_ROOT;

var dbdir       = rootdir + '/components/database';

var dbwrite     = require(dbdir + '/dbwrite');
var queries     = require(dbdir + '/queries');
var dbwrapper   = require(dbdir + '/dbwrapper')();
    dbwrapper.mixin(dbwrite).mixin(queries);

var constants   = require(dbdir + '/constants');

var async       = require('async');


// get the user name from the command line arguments
if(process.argv.length <= 3) {
    console.log('USAGE: ');
    console.log(" >  ./tools/db/newScene 'user_name' 'scene_name'");
    process.exit(0);
}
var username = process.argv[2];
var scenename = process.argv[3];

// now issue the database command and inform the user
// of the success or failure of the command
var db = dbwrapper.db();
db.verbose = false;
var user_id = null;
async.waterfall([
async.apply(db.newScene.bind(db), {
        scene_name: scenename,
        user_name: username,
        scene_json: constants.default_scene_json,
}),
function(contWaterfall) {
    console.log('created new scene');
    contWaterfall(null);
},
], function(err) {
    db.close();
    if(err) {
        throw err;
    }
});